import { ImportError } from "./importErrors";
import { decodeText, MAX_IMPORT_BYTES } from "./importFormats";
import { parseArchivePageXml, parseFile } from "./importers";
import { normalizeLanguage } from "./speech";
import type { ParsedBook } from "./types";

type ArchiveFile = { name?: string; size?: string; private?: boolean | string; source?: string };
type ArchiveMetadata = {
  is_restricted?: boolean | string;
  is_lending?: boolean | string;
  lendingInfo?: { is_lending?: boolean | string };
  metadata?: { title?: string | string[]; creator?: string | string[]; language?: string | string[]; "access-restricted-item"?: boolean | string };
  files?: ArchiveFile[];
};

export function archiveIdentifier(rawUrl: string): string | undefined {
  try {
    const url = new URL(rawUrl.trim());
    if (!['archive.org', 'www.archive.org'].includes(url.hostname.toLowerCase()) || !['http:', 'https:'].includes(url.protocol)) return;
    const match = url.pathname.match(/^\/details\/([a-zA-Z0-9][a-zA-Z0-9._-]*)(?:\/)?$/);
    return match?.[1];
  } catch { return; }
}

function first(value?: string | string[]): string | undefined {
  const text = (Array.isArray(value) ? value[0] : value)?.trim();
  return text || undefined;
}

function restricted(value: boolean | string | undefined): boolean {
  return value === true || value === 'true' || value === '1';
}

export function archiveCandidates(metadata: ArchiveMetadata): ArchiveFile[] {
  if (restricted(metadata.is_restricted) || restricted(metadata.is_lending) || restricted(metadata.lendingInfo?.is_lending)
    || restricted(metadata.metadata?.['access-restricted-item'])) {
    throw new ImportError("This Internet Archive item is access-restricted and cannot be imported.", "restricted", "archive_restricted", "direct_fetch");
  }
  return (metadata.files ?? []).filter((file) => file.name && !restricted(file.private) && file.source !== "metadata"
    && !/[\\/]/.test(file.name) && !file.name.includes("..") && !/(?:_meta|_files|_reviews|_log|_readme)\.txt$/i.test(file.name))
    .map((file) => ({ file, rank: /_djvu\.txt$/i.test(file.name!) ? 0
      : /\.txt$/i.test(file.name!) && !/(?:_meta|_files)\.txt$/i.test(file.name!) ? 1
        : /_djvu\.xml$/i.test(file.name!) ? 2
          : /\.epub$/i.test(file.name!) ? 3
            : /\.pdf$/i.test(file.name!) ? 4 : 5 }))
    .filter(({ rank }) => rank < 5)
    .sort((a, b) => a.rank - b.rank || (a.file.source === "derivative" ? -1 : 1))
    .map(({ file }) => file);
}

// Conservative OCR cleanup: remove scan-only markers and isolated folio numbers,
// join wrapped lines, and retain blank lines between paragraphs.
export function normalizeArchiveOcr(text: string): string {
  return text.replace(/\r\n?/g, "\n").replace(/\f/g, "\n\n")
    .split("\n")
    .map((line) => line.replace(/[\t \u00a0]+/g, " ").trim())
    .filter((line) => !/^(?:digitized by (?:the )?(?:internet archive|google)|generated by (?:the )?internet archive|https?:\/\/archive\.org\/details\/\S+|\[?blank page\]?)$/i.test(line)
      && !/^\[?\d{1,4}\]?$/.test(line))
    .join("\n")
    .replace(/([^\W\d_]{2,})-\n([^\W\d_]{2,})/gu, "$1$2")
    .replace(/([^\n])\n(?!\n)([^\n])/g, "$1 $2")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}

export async function importInternetArchive(rawUrl: string): Promise<{ parsed: ParsedBook; identifier: string; sourceUrl: string; size: number }> {
  const identifier = archiveIdentifier(rawUrl);
  if (!identifier) throw new ImportError("Enter an Internet Archive book URL (archive.org/details/BOOK_ID).", "unsupported", "invalid_archive_url", "validation");
  const base = `/api/internet-archive/${encodeURIComponent(identifier)}`;
  const response = await fetch(base);
  if (!response.ok) throw new ImportError(response.status === 403 ? "This Internet Archive item is access-restricted and cannot be imported." : "Internet Archive metadata could not be loaded.", response.status === 403 ? "restricted" : "network", "archive_metadata_failed", "direct_fetch", "unknown", response.status);
  const metadata = await response.json() as ArchiveMetadata;
  const candidates = archiveCandidates(metadata);
  if (!candidates.length) throw new ImportError("This Internet Archive item has no usable public TXT, DjVu XML, EPUB, or PDF text derivative.", "insufficient_content", "archive_no_text", "conversion");
  const title = first(metadata.metadata?.title) ?? identifier;
  const author = first(metadata.metadata?.creator);
  const language = normalizeLanguage(first(metadata.metadata?.language));
  const coverFile = (metadata.files ?? []).find((file) => file.name && /(?:__ia_thumb|_thumb|cover)\.(?:jpe?g|png)$/i.test(file.name) && !restricted(file.private));
  const sourceUrl = `https://archive.org/details/${identifier}`;
  let oversized = false;
  for (const file of candidates) {
    if (Number(file.size) > MAX_IMPORT_BYTES) { oversized = true; continue; }
    const download = await fetch(`${base}/file?name=${encodeURIComponent(file.name!)}`);
    if (!download.ok) throw new ImportError(download.status === 401 || download.status === 403 ? "This Internet Archive file is restricted." : download.status === 413 ? "This document is larger than the 100 MB import limit." : "The Internet Archive file could not be downloaded.", download.status === 401 || download.status === 403 ? "restricted" : download.status === 413 ? "file_too_large" : "network", "archive_download_failed", "direct_fetch", "unknown", download.status);
    const blob = await download.blob();
    if (blob.size > MAX_IMPORT_BYTES) throw new ImportError("This document is larger than the 100 MB import limit.", "file_too_large", "file_too_large", "read");
    let parsed: ParsedBook;
    try {
      if (/_djvu\.xml$/i.test(file.name!)) {
        parsed = parseArchivePageXml(decodeText(await blob.arrayBuffer(), download.headers.get("content-type") ?? ""), title, normalizeArchiveOcr);
      } else if (/\.txt$/i.test(file.name!)) {
        const text = decodeText(await blob.arrayBuffer(), download.headers.get("content-type") ?? "");
        parsed = await parseFile(new File([normalizeArchiveOcr(text)], `${identifier}.txt`, { type: "text/plain" }));
      } else parsed = await parseFile(new File([blob], file.name!));
    } catch (error) {
      // A derivative can be present but contain no readable text. Try the next
      // publicly available format; never fall back after an access error.
      if (error instanceof ImportError && error.category === "insufficient_content") continue;
      throw error;
    }
    if (coverFile?.name && !parsed.cover) {
      try {
        const cover = await fetch(`${base}/file?name=${encodeURIComponent(coverFile.name)}`);
        if (cover.ok) parsed.cover = await cover.blob();
      } catch { /* Missing covers do not prevent import. */ }
    }
    return { parsed: { ...parsed, title, author: author ?? parsed.author, language: language ?? parsed.language }, identifier, sourceUrl, size: blob.size };
  }
  if (oversized) throw new ImportError("Available Internet Archive text derivatives exceed the 100 MB import limit.", "file_too_large", "archive_files_too_large", "read");
  throw new ImportError("This Internet Archive item has no usable readable text derivative.", "insufficient_content", "archive_no_text", "conversion");
}
